INSERT INTO SEG_USUARIO(ID_USUARIO, NM_USUARIO, DS_EMAIL, COD_SENHA) VALUES (SEQ_SEG_USUARIO.NEXTVAL, 'Nina Brown', 'nina@gmail.com', '$2a$10$NYFZ/8WaQ3Qb6FCs.00jce4nxX9w7AkgWVsQCG6oUwTAcZqP9Flqu');
INSERT INTO SEG_USUARIO(ID_USUARIO, NM_USUARIO, DS_EMAIL, COD_SENHA) VALUES (SEQ_SEG_USUARIO.NEXTVAL, 'Leia Red', 'leia@gmail.com', '$2a$10$NYFZ/8WaQ3Qb6FCs.00jce4nxX9w7AkgWVsQCG6oUwTAcZqP9Flqu');

INSERT INTO SEG_FUNCAO(ID_FUNCAO, NM_FUNCAO) VALUES (SEQ_SEG_FUNCAO.NEXTVAL, 'ROLE_OPERATOR');
INSERT INTO SEG_FUNCAO(ID_FUNCAO, NM_FUNCAO) VALUES (SEQ_SEG_FUNCAO.NEXTVAL, 'ROLE_ADMIN');

INSERT INTO SEG_USUARIO_FUNCAO(ID_USUARIO, ID_FUNCAO) VALUES (1, 1);
INSERT INTO SEG_USUARIO_FUNCAO(ID_USUARIO, ID_FUNCAO) VALUES (2, 1);
INSERT INTO SEG_USUARIO_FUNCAO(ID_USUARIO, ID_FUNCAO) VALUES (2, 2);